### ISSUE TITLE
keep getting this error in replit

### ISSUE THREAD

**Issue by KatiIsHere** [Atluzka/account-gen-bot#16]
2024-12-18 14:39:59 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 816, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 758, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/discorddbnot/main.py", line 279, in <module>
    bot.run(config['token'])
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/nix/store/418nyl05dzqb57brvqjd1g22p27xyqbq-python3-3.10.14/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/418nyl05dzqb57brvqjd1g22p27xyqbq-python3-3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 858, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 786, in start
    await self.login(token)
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 620, in login
    data = await self.http.static_login(token)
  File "/home/runner/discorddbnot/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 820, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by Atluzka** [comment]
The discord token u put is invalid. U need a **DISCORD BOT** token not a discord account token.
