### ISSUE TITLE
Issue when adding accounts

### ISSUE THREAD

**Issue by d0nc4p** [Atluzka/account-gen-bot#6]
Hello, 

Whenever I try to add any accounts, text, etc to an existent account it gives me this error:

2023-10-02 12:03:22] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'add'
Traceback (most recent call last):
  File "C:\Users\donca\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\donca\OneDrive\Desktop\account-gen-bot-main\bot.py", line 215, in addacc
    if getFileName(file).lower() == service.lower():
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'lower'

let me know if there is a way to fix this issue or if I am missing something, everything else works as expected.

Thank you.

**Comment by Atluzka** [comment]
Sorry for late response I was away for a while. The add command is broken. I'm already working on a new version which changes a lot of things, update will come soon.
